dbt_transformations:
  outputs:
    dev:
      account: XNDEVHR-PB86455
      database: PHARMA_PLATFORM
      password: Switch@20262026!
      role: SYSADMIN
      schema: DBT_SCHEMA
      threads: 1
      type: snowflake
      user: TECHNICALDEVELOPER
      warehouse: WH_PHARMA
  target: dev
