version: 2

sources:
  - name: raw
    database: PHARMA_PLATFORM
    schema: raw
    config:
      enabled: true
    tables:
      - name: hcp_master_raw
        columns:
          - name: hcp_id
            tests:
              - not_null
          - name: specialty
            tests:
              - not_null
          - name: territory
            tests:
              - not_null
          - name: engagement_tier
            tests:
              - not_null
      - name: product_master_raw  # enabled
      - name: rx_events_raw  # not enabled
        config:
          enabled: true